language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"root",pwd:"_meeky010",roles:["readWrite"]});'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn test

after_script:  
  - yarn coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
